channels: [Phase3D] # may be null in which case all channels will be stitched
preprocessing:
  fliplr: true
  flipud: false
postprocessing:
  fliplr: false
  flipud: true
total_translation: # translation distance in (x, y) in pixels for each image
  0/2/000000:
  - 0.0
  - 39.7
  0/2/000001:
  - 883.75
  - 39.7
  0/2/001000:
  - 1.8
  - 920.5
  0/2/001001:
  - 885.55
  - 920.7
# Instead of computing a total (x, y) shift for each image using estimate-stitch
# you can also supply column_translation and row_translation as (x, y) lists
# that will be applied to all images. column_translation and row_translation
# should be approximately (950, 0) and (0, 950) for 1000x1000 images with 5% overlap.
# This method of stitching images is being deprecated as the stage often does not
# make reproducible movements.
column_translation:
row_translation:
