# This is an example settings file for combined label-free and light--sheet
# acquisition on the mantis microscope.

# Here we define variables (YAML anchors) which will be used later, for
# convenience
LCA_DAC: &LCA_DAC 'TS1_DAC01'
LCB_DAC: &LCB_DAC 'TS1_DAC02'
MCL_DAC: &MCL_DAC 'TS1_DAC06'
AP_GALVO_DAC: &AP_GALVO_DAC 'TS2_DAC03'

# The label-free and the light-sheet acquisition share the same time settings
# which are controlled by the mantis acquisition engine. Data are acquired in
# TPCZYX order. `time_interval_s` is the minimum time between positions, i.e.
# the acquisition will continue immediately if the elapsed time to acquire all
# positions is greater
time_settings:
  num_timepoints: 10
  time_interval_s: 60

# Define channel settings for the label-free acquisition. All channels must be
# within the same config group. `exposure_time_ms` must be a list of length
# equal to the number of channels. Currently, however, the acquisition software
# does not support different exposure times for the label-free channels.
lf_channel_settings:
  exposure_time_ms: [10, 10, 10, 10, 10]
  channel_group: 'Channel - LF'
  channels: ['State0', 'State1', 'State2', 'State3', 'State4']
  use_sequencing: True

# Define slice (i.e. z-stack) settings for the label-free acquisition.
lf_slice_settings:
  z_stage_name: 'MCL Piezo'
  z_start: -10
  z_end: 10
  # When using 0.52 NA transmission light illumination, Nyquist sampling of the
  # axial dimension will be achieved by using (450*1.4)/(1.35^2 + 0.52^2) = 300 nm
  # steps in sample space. We can achieve this by using (300 nm)*1.4/2 = 210 nm
  # steps of the mirror due to the 1.4x magnification of the remote volume and the
  # fact that the optical path length is extended by twice the mirror's motion.
  #
  # Here we choose to oversample the data to match the light-sheet axial
  # sampling. After deskewing and 3x binning, the light-sheet samples are
  # spaced by ~205 nm, so we choose (205 nm)*1.4/2 = 143 nm mirror steps.
  z_step: 0.143
  use_sequencing: True

# Define channel settings for the light-sheet acquisition. Channels may have
# different exposure time
ls_channel_settings:
  exposure_time_ms: [10, 10]
  channel_group: 'Channel - LS'
  channels: ['GFP EX488 EM525-45', 'mCherry EX561 EM600-37']
  use_sequencing: False

# Define slice (i.e. z-stack) settings for the light-sheet acquisition.
ls_slice_settings:
  z_stage_name: 'AP Galvo'
  # 170 um scan range matches the label-free field of view. Corresponds to
  # ~5.5 V based on 31.3 um/V conversion factor
  z_start: -85  # in micrometers
  z_end: 85
  # Nyquist sampling of this dimensions will be achieved by using ~116 nm steps.
  # When imaging live cells we chose to undersample this dimension to decrease
  # photobleaching and photodamage.
  z_step: 0.313  # equivalent to 10 mV
  use_sequencing: True

# Microscope settings which will be applied when the label-free acquisition is
# initialized
lf_microscope_settings:
  # ROI may be omitted or blank; in this case the ROI will not be changed
  roi:
  # Config group settings to apply. Must be a list of
  # [config_group, config_name] pairs
  config_group_settings:
    - ['Imaging Path', 'Label-free']
    - ['Channel - LS', 'External Control']
    # need to set first channel for falling edge sequencing
    - ['Channel - LF', 'State0']
  # Device property settings to apply. Must be a list of
  # [device_name, property_name, property_value] sets
  device_property_settings:
    - ['Oryx', 'Line Selector', 'Line5']
    - ['Oryx', 'Line Mode', 'Output']
    - ['Oryx', 'Line Source', 'ExposureActive']
    - ['Oryx', 'Line Selector', 'Line2']
    - ['Oryx', 'Line Mode', 'Input']
    - ['Oryx', 'Trigger Source', 'Line2']
    - ['Oryx', 'Trigger Mode', 'On']
    # required for external triggering at max fps
    - ['Oryx', 'Trigger Overlap', 'ReadOut']
    - ['Oryx', 'Frame Rate Control Enabled', '0']
  # Device property settings which will be applied when the acquisition is
  # finished.
  reset_device_properties:
    - ['Oryx', 'Trigger Mode', 'Off']
    - ['XYStage:XY:31', 'MotorSpeedX-S(mm/s)', 5.75]
    - ['XYStage:XY:31', 'MotorSpeedY-S(mm/s)', 5.75]
  # Device property settings which enable z sequencing
  z_sequencing_settings:
    - [*MCL_DAC, 'Sequence', 'On']
  # Device property settings which enable channel sequencing
  channel_sequencing_settings:
    - [*LCA_DAC, 'Sequence', 'On']
    - [*LCB_DAC, 'Sequence', 'On']
  # Autofocus properties. `autofocus_stage` is the coarse stage which will be
  # moved between positions to ensure that the autofocus mechanism is within
  # range
  use_autofocus: True
  autofocus_stage: 'ZDrive'
  autofocus_method: 'PFS'

# Microscope settings which will be applied when the light-sheet acquisition is
# initialized
ls_microscope_settings:
  roi: [0, 896, 2048, 256]
  device_property_settings:
    - ['Prime BSI Express', 'ReadoutRate', '200MHz 11bit']
    - ['Prime BSI Express', 'Gain', '1-Full well']
    - ['Prime BSI Express', 'TriggerMode', 'Edge Trigger']
    - ['Prime BSI Express', 'ExposeOutMode', 'Rolling Shutter']
    # Illuminate sample only when all rows are exposing, aka pseudo global shutter
    - ['TS2_TTL1-8', 'Blanking', 'On']
  reset_device_properties:
    - ['Prime BSI Express', 'TriggerMode', 'Internal Trigger']
    - ['TS2_TTL1-8', 'Blanking', 'Off']
  z_sequencing_settings:
    - [*AP_GALVO_DAC, 'Sequence', 'On']
  use_o3_refocus: True
  o3_refocus_config: ['Channel - LS', 'GFP EX488 EM525-45']
  o3_refocus_interval_min: 10
