# Setup
setup:
  properties:
    - ['XY', 'Velocity', '10000']
    - ['PiezoZ', 'UseSequences', 'Yes']

stage_positions:
  - x: 0
    y: 0
    name: "Pos0"
    properties:
      - ['ObjectiveZ', 'Position', '0']

# Define time plan
time_plan:
  prioritize_duration: true
  interval: 10
  loops: 5

# Define z plan
z_plan:
  top: 10
  bottom: -10
  step: 0.174
  go_up: true

# Define channels
channels:
- config: BF
  group: Channel
  exposure: 10.0
  do_stack: true
  z_offset: 0.0
  acquire_every: 1
  camera: null

# Define axis order
axis_order:
- t
- p
- c
- z

autofocus_plan: null
keep_shutter_open_across: []

# Define metadata per microscope
metadata:
  pymmcore_widgets:
    version: 0.10.2.dev23+g22b8c0aff.d20260106
  mantis:
    reset_hardware_sequencing_settings:
      - ['PiezoZ', 'UseSequences', 'No']
    autofocus:
      enabled: false
      method: demo-PFS
      stage: ObjectiveZ
    position_update:
      enabled: true
      update_channel: 0
      z_device: ObjectiveZ
      dynatrack:
        scale_yx: 0.1494
        scale_z: 0.174
        # shift_limits:
        #   z: [0.5, 2.0]
        #   y: [2.0, 10.0]
        #   x: [2.0, 10.0]
        tracking_interval: 1
        shift_log_path: shift_log.csv
